### ISSUE TITLE
RFE - Can we integrate this script with our xsos tool we use to analyze sos report!

### ISSUE THREAD

**Issue by vgunasek** [waldirio/sos_analyze#37]
Hello Buddy,

Is it possible can we integrate this script with xsos. 
-->   https://github.com/ryran/xsos

**Comment by waldirio** [comment]
Hello @vgunasek 

Thanks for your feedback and let me do some questions that will help on this way/answer

What feature is/are nice to you on xsos?
A: 
Is it possible to generate a plan text on xsos? (without color formating)
A: 
Which features do you feel missing on xsos?
A:

That will help us to understand and then move forward.

Thank you

**Comment by vgunasek** [comment]
What feature is nice to you on xsos?
A:  Getting specific reports using flags eg xsos -c for CPU.
Is it possible to generate a plan text on xsos?
A: Not sure buddy, I have never tried to get output in text file.
Which features do you feel missing on xsos?
A: Analyzing the logs and consolidated report like what we do now like errors, virt-who config and so on.

**Comment by waldirio** [comment]
Hey
I'm checking xsos atm and using the flag -all (all information) I can see there are some overlap of info, however, the approach is diff because we are collecting much more info focused on Satellite.

I'll archive this request for now and in the future, we can do a double check again.

Thanks for the heads up and request.
